services:
  - type: web
    name: sentiment-analysis
    env: python
    buildCommand: cd 'projekt dipllome/render_project' && pip install -r requirements.txt
    startCommand: cd 'projekt dipllome/render_project' && gunicorn Source.app:app
