services:
  - type: web
    name: sentiment-analysis
    env: python
    root_dir: projekt\ dipllome/render_project
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 2 --worker-class sync --bind 0.0.0.0:$PORT wsgi:app
